In [1]:
%matplotlib inline


Tensors
--------------------------------------------
Tensors 는 arrays, matrices와 매우 유사한 특화된 자료 구조이다.      
PyTorch에서, model의 inputs, outputs, parameters를 인코딩하기 위해 tensor를 사용한다.  
<br/>
Tensors 는 NumPy의 `ndarray`와 유사하지만, GPUs 또는 기타 특수 하드웨어에서 컴퓨팅 가속화를 위해 동작한다는 점에서 `ndarray`와 다르다.  
만약 `ndarray`에 익숙하다면, 좀 더 편하게 Tensor API를 사용할 수 있다.

In [2]:
import torch
import numpy as np

Tensor Initialization
~~~~~~~~~~~~~~~~~~~~~

Tensors는 다양한 방법을 사용해 초기화된다. 다음의 예제를 한번 보자:

**Directly from data**

Tensors는 data에서 바로 만들어지고, data type은 자동으로 지정된다.



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print("x_data : \n{0}\n".format(x_data))

x_data : 
tensor([[1, 2],
        [3, 4]])



**From a NumPy array**

Tensors는 NumPy arrays를 사용해서 만들 수 있다. (and vice versa - see `bridge-to-np-label`)



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

새로운 tensor는 명시적으로 override되지 않는 한, argument tensor의 속성(shape, datatype)을 유지한다.


In [5]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지한다.
print("x_ones : \n{0}\n".format(x_ones))

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 datatype을 override했다.
print("x_rand :\n{0}\n".format(x_rand))

x_ones : 
tensor([[1, 1],
        [1, 1]])

x_rand :
tensor([[0.6931, 0.6215],
        [0.2459, 0.0442]])



**With random or constant values:**

``shape``은 tensor의 차원을 나타내고, datatype은 tuple이다.  
아래의 함수에서, ``shape``이 output tensor의 차원을 나타내는 것을 볼 수 있다.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("Random Tensor: \n{0}\n".format(rand_tensor))
print("Ones Tensor: \n{0}\n".format(ones_tensor))
print("Zeros Tensor: \n{0}\n".format(zeros_tensor))

Random Tensor: 
tensor([[0.0046, 0.4561, 0.1619],
        [0.9186, 0.7194, 0.3573]])

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])



--------------




Tensor Attributes
~~~~~~~~~~~~~~~~~

Tensor attributes는 tensor의 shape, datatype, 그리고 tensor가 저장되는 device(CPU or GPU)를 나타낸다.



In [7]:
tensor = torch.rand(3,4)

print("Shape of tensor: {0}".format(tensor.shape))
print("Datatype of tensor: {0}".format(tensor.dtype))
print("Device tensor is stored on: {0}".format(tensor.device))

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




Tensor Operations
~~~~~~~~~~~~~~~~~

100개 이상의 tensor 연산이 존재한다.
`here <https://pytorch.org/docs/stable/torch.html>`  

각 연산들은 GPU에서 실행될 수 있다. (CPU보다 속도가 빠르다)




In [8]:
# GPU를 사용할 수 있는 환경이라면, tensor를 GPU로 옮길 수 있다.
if torch.cuda.is_available():
  tensor = tensor.to('cuda')


list에서 사용하는 몇 가지 연산을 수행해보자.  
만약 NumPy API에 익숙하다면, Tensor API를 사용하기 쉬울 것이다.


**Standard numpy-like indexing and slicing:**



In [9]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 # 1번 column을 0으로 바꾸기
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors**  
<br/>
``torch.cat``로 tensor들을 연결하는 concatenate 연산을 수행할 수 있다.  
<br/>
`torch.stack <https://pytorch.org/docs/stable/generated/torch.stack.html>` 역시 tensor들을 연결하기 위해 사용할 수 있다. ``torch.cat``과는 미묘하게 다르다.


In [10]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Multiplying tensors**



In [11]:
# element-wist product
print("tensor.mul(tensor) : \n{0}\n".format(tensor.mul(tensor)))
# 또 다른 방법:
print("tensor * tensor : \n{0}\n".format(tensor * tensor))

tensor.mul(tensor) : 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor * tensor : 
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])




두 개의 tensor들로 matrix multiplication을 계산한다.


In [12]:
print("tensor.matmul(tensor.T) \n {0} \n".format(tensor.matmul(tensor.T)))
# 또 다른 방법:
print("tensor @ tensor.T \n {0} \n".format(tensor @ tensor.T))

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 



**In-place operations**
<br/>
메소드 뒤에 ``_``를 붙이면 계산 결과를 반환하고, 그 값을 해당 변수에 저장한다.    
<br/>
예시: ``x.copy_(y)``, ``x.t_()``  
      --> ``x``가 바뀔 것이다.    


In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div class="alert alert-info"><h4>Note</h4><p>In-place 연산을 사용해서 메모리를 절약할 수 있다. 그러나, 계산했던 기록이 즉각적으로 없어지기 때문에 미분을 계산할 때 문제가 될 수 있다. 그러므로, in-place 연산은 권장하지 않는다.</p></div>


--------------





Bridge with NumPy
~~~~~~~~~~~~~~~~~
Tensors와 NumPy arrays는 메모리 위치를 공유한다.
그래서 tensor를 바꾸면, NumPy array도 바뀐다.
역으로 NumPy array를 바꾸면 tensor도 바뀐다.


Tensor to NumPy array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [14]:
t = torch.ones(5)
print("t: {0}".format(t))
n = t.numpy()
print("n: {0}".format(n))

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]



Tensor를 바꾸면 NumPy array도 바뀐다.


In [15]:
t.add_(1)
print("t: {0}".format(t))
print("n: {0}".format(t))

t: tensor([2., 2., 2., 2., 2.])
n: tensor([2., 2., 2., 2., 2.])


NumPy array to Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [16]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy array를 바꾸면 tensor도 바뀐다.


In [17]:
np.add(n, 1, out=n)
print("t: {0}".format(t))
print("n: {0}".format(n))

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
